<?php

namespace FoodCorner\ReservationnBundle\Repository;

/**
 * TableeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableeRepository extends \Doctrine\ORM\EntityRepository
{
}
